<?php

namespace App\Traits;

trait FillAuthor{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model){
            $model->user_id = auth()->user()->id;
        });
    }
}
